# Generated by Django 4.1.4 on 2023-03-01 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductImage",
        ),
    ]
