# Generated by Django 4.1.4 on 2023-03-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_delete_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="DiscountPrice",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                verbose_name="Discount Price",
            ),
        ),
    ]
