# Generated by Django 4.1.4 on 2023-03-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_discountprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="Cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Cost",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="DiscountPrice",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Discount Price",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="photo/"),
        ),
    ]
